---
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
http: !include includes/http.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
shell_command: !include includes/shell_commands.yaml

person: !include includes/persons.yaml
zone: !include includes/zones.yaml
sensor: !include includes/sensors.yaml
light: !include includes/lights.yaml

counter:
  gas_counter:
    name: Gas Counter

lovelace:
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/minimalist/ui.yaml
