background: var(--background-image)
title: Appart
views:
- badges:
  - entity: person.pierre
  - entity: sun.sun
  cards:
  - entities:
    - entities:
      - entity: light.canape
        secondary_info: '{{relative_time(states.light.canape.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      - entity: light.fauteuil
        secondary_info: '{{relative_time(states.light.fauteuil.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      head:
        color_picker: true
        entity: light.living_room_lights
        hide_when_off: false
        icon: mdi:sofa
        name: Salon
        toggle: true
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.chambre
        secondary_info: '{{relative_time(states.light.chambre.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      head:
        color_picker: true
        entity: light.bedroom_lights
        hide_when_off: false
        icon: mdi:bed-king
        name: Chambre
        toggle: true
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Lights
    type: entities
  - entity: weather.appart
    type: weather-forecast
  - entity: light.chambre
    type: light
  - entity: media_player.spotify_pierre_berger
    type: media-control
  - entity: media_player.salon
    type: media-control
  - entity: sensor.netatmo_statmet_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Saint Germain
    type: sensor
  - entities:
    - entities:
      - input_select.theme
      head:
        entity: input_boolean.dark_mode
        name: Dark Mode
      type: custom:fold-entity-row
    show_header_toggle: false
    type: entities
  - entities:
    - entity: sensor.tram_a_la_poya
      image: https://www.tag.fr/uploads/FichesHoraires/47/54_841_A_100px.png
      name: '{% set destination = state_attr(''sensor.tram_a_la_poya'', ''destination'')
        %} {% if destination != None %} Tram A - {{ destination }} {% else %} {{ state_attr(''sensor.tram_a_la_poya'',
        ''name'') }} {% endif %}'
      state: "{{ states('sensor.tram_a_la_poya') }} {% set unit = state_attr('sensor.tram_a_la_poya',\
        \ 'unit_of_measurement') %} {% if unit != None %} {{ unit }} {% endif %} \n"
      type: custom:template-entity-row
    - entity: sensor.tram_a_l_etoile
      image: https://www.tag.fr/uploads/FichesHoraires/47/54_841_A_100px.png
      name: '{% set destination = state_attr(''sensor.tram_a_l_etoile'', ''destination'')
        %} {% if destination != None %} Tram A - {{ destination }} {% else %} {{ state_attr(''sensor.tram_a_l_etoile'',
        ''name'') }} {% endif %}'
      state: "{{ states('sensor.tram_a_l_etoile') }}  {% set unit = state_attr('sensor.tram_a_l_etoile',\
        \ 'unit_of_measurement') %} {% if unit != None %} {{ unit }} {% endif %} \n"
      type: custom:template-entity-row
    - entity: sensor.tram_b_oxford
      image: https://www.tag.fr/uploads/FichesHoraires/cc/55_848_B-100px.png
      name: '{% set destination = state_attr(''sensor.tram_b_oxford'', ''destination'')
        %} {% if destination != None %} Tram B - {{ destination }} {% else %} {{ state_attr(''sensor.tram_b_oxford'',
        ''name'') }} {% endif %}'
      secondary: 'Next {{ state_attr(''sensor.tram_b_oxford'', ''next'') }} {% set
        unit = state_attr(''sensor.tram_b_oxford'', ''unit_of_measurement'') %} {%
        if unit != None %} {{ unit }} {% endif %} '
      state: "{{ states('sensor.tram_b_oxford') }} {% set unit = state_attr('sensor.tram_b_oxford',\
        \ 'unit_of_measurement') %} {% if unit != None %} {{ unit }} {% endif %} \n"
      type: custom:template-entity-row
    - entity: sensor.tram_b_plaine_des_sports
      image: https://www.tag.fr/uploads/FichesHoraires/cc/55_848_B-100px.png
      name: '{% set destination = state_attr(''sensor.tram_b_plaine_des_sports'',
        ''destination'') %} {% if destination != None %} Tram B - {{ destination }}
        {% else %} {{ state_attr(''sensor.tram_b_plaine_des_sports'', ''name'') }}
        {% endif %}'
      state: '{{ states(''sensor.tram_b_plaine_des_sports'') }} {% set unit = state_attr(''sensor.tram_b_plaine_des_sports'',
        ''unit_of_measurement'') %} {% if unit != None %} {{ unit }} {% endif %}

        '
      type: custom:template-entity-row
    - entity: sensor.c1_cite_jean_mace
      image: https://www.tag.fr/uploads/FichesHoraires/11/60_867_C1-100px.png
    type: entities
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - icon: mdi:json
    icon_height: 0px
    name: Convert lovelace
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: shell_command.convert_lovelace
    type: button
  - entities:
    - entity: sensor.speedtest_download
    - entity: sensor.speedtest_upload
    - entity: sensor.speedtest_ping
    title: Network
    type: entities
  icon: mdi:home-automation
- badges: []
  cards:
  - entity: weather.appart
    type: weather-forecast
  - detail: 1
    entity: sensor.netatmo_statmet_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Netatmo extérieur
    type: sensor
  - entity: sensor.netatmo_statmet_interieur_temperature
    graph: line
    name: Netatmo intérieur
    type: sensor
  icon: mdi:weather-cloudy
  path: weather
  title: Weather
- badges: []
  cards:
  - entities:
    - entity: sensor.interrupteur_battery_level
      name: Interrupteur
    - entity: sensor.netatmo_statmet_exterieur_battery_percent
      name: Netatmo extérieur
    - entity: sensor.netatmo_statmet_exterieur_pluviometre_battery_percent
      name: Neatmo Pluviometre
    - entity: sensor.iphone_de_pierre_battery_level
    type: entities
  icon: mdi:battery-50
  path: power
  title: Power
- badges:
  - entity: person.pierre
  cards:
  - entities:
    - entity: person.pierre
    type: map
  - entities:
    - sensor.iphone_de_pierre_geocoded_location
    type: entities
  icon: mdi:account
