background: var(--background-image)
title: Appart
views:
- badges:
  - entity: person.pierre
  - entity: sun.sun
  cards:
  - entities:
    - entity: light.chambre
    - entity: light.canape
    - entity: light.fauteuil
    title: Lights
    type: entities
  - entity: weather.appart
    type: weather-forecast
  - entity: light.chambre
    type: light
  - entity: media_player.spotify_pierre_berger
    type: media-control
  - entity: sensor.netatmo_statmet_interieur_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Saint Germain
    type: sensor
  - entities:
    - entities:
      - input_select.theme
      head:
        entity: input_boolean.dark_mode
        name: Dark Mode
      type: custom:fold-entity-row
    show_header_toggle: false
    type: entities
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - icon: mdi:json
    icon_height: 20px
    name: Convert lovelace
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: shell_command.convert_lovelace
    type: button
  icon: mdi:home-automation
