background: var(--background-image)
title: Appart
views:
- badges:
  - entity: person.pierre
  - entity: sun.sun
  cards:
  - entities:
    - entity: light.chambre
    - entity: light.canape
    - entity: light.fauteuil
    title: Lights
    type: entities
  - entity: weather.appart
    type: weather-forecast
  - entity: light.chambre
    type: light
  - entity: media_player.spotify_pierre_berger
    type: media-control
  - entity: sensor.netatmo_statmet_interieur_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Saint Germain
    type: sensor
  - entities:
    - entities:
      - input_select.theme
      head:
        entity: input_boolean.dark_mode
        name: Dark Mode
      type: custom:fold-entity-row
    show_header_toggle: false
    type: entities
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - icon: mdi:json
    icon_height: 20px
    name: Convert lovelace
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: shell_command.convert_lovelace
    type: button
  - entities:
    - entity: sensor.speedtest_download
    - entity: sensor.speedtest_upload
    - entity: sensor.speedtest_ping
    title: Network
    type: entities
  icon: mdi:home-automation
- badges: []
  cards:
  - entity: weather.appart
    type: weather-forecast
  - detail: 1
    entity: sensor.netatmo_statmet_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Netatmo extérieur
    type: sensor
  - entity: sensor.netatmo_statmet_interieur_temperature
    graph: line
    name: Netatmo intérieur
    type: sensor
  icon: mdi:weather-cloudy
  path: weather
  title: Weather
- badges: []
  cards:
  - entities:
    - entity: sensor.interrupteur_battery_level
      name: Interrupteur
    - entity: sensor.netatmo_statmet_exterieur_battery_percent
      name: Netatmo extérieur
    - entity: sensor.netatmo_statmet_exterieur_pluviometre_battery_percent
      name: Neatmo Pluviometre
    - entity: sensor.iphone_de_pierre_battery_level
    type: entities
  icon: mdi:battery-50
  path: power
  title: Power
- badges:
  - entity: person.pierre
  cards:
  - entities:
    - entity: sensor.iphone_de_pierre_geocoded_location
    type: map
  - entities:
    - sensor.iphone_de_pierre_geocoded_location
    type: entities
  icon: mdi:account
