background: var(--background-image)
title: Appart
views:
- badges:
  - entity: person.pierre
  - entity: sun.sun
  cards:
  - entities:
    - entities:
      - entity: light.canape
        secondary_info: '{{relative_time(states.light.canape.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      - entity: light.fauteuil
        secondary_info: '{{relative_time(states.light.fauteuil.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      head:
        color_picker: true
        entity: light.living_room_lights
        hide_when_off: false
        icon: mdi:sofa
        name: Salon
        toggle: true
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.chambre
        secondary_info: '{{relative_time(states.light.chambre.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      - entity: light.bureau
        secondary_info: '{{relative_time(states.light.bureau.last_changed)}} ago'
        type: custom:secondaryinfo-entity-row
      head:
        color_picker: true
        entity: light.bedroom_lights
        hide_when_off: false
        icon: mdi:bed-king
        name: Chambre
        toggle: true
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Lights
    type: entities
  - entity: weather.appart
    type: weather-forecast
  - entity: light.chambre
    type: light
  - entity: media_player.spotify_pierre_berger
    type: media-control
  - entity: media_player.salon
    type: media-control
  - entities:
    - entities:
      - input_select.theme
      head:
        entity: input_boolean.dark_mode
        name: Dark Mode
      type: custom:fold-entity-row
    show_header_toggle: false
    type: entities
  - cards:
    - detail: 1
      entity: sensor.lumi_lumi_weather_32f13908_temperature
      graph: line
      hours_to_show: 24
      name: Living room
      type: sensor
    - detail: 1
      entity: sensor.lumi_lumi_weather_temperature
      graph: line
      hours_to_show: 24
      name: Outside
      type: sensor
    columns: 2
    square: false
    type: grid
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - icon: mdi:json
    icon_height: 0px
    name: Convert lovelace
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: shell_command.convert_lovelace
    type: button
  icon: mdi:home-automation
- badges: []
  cards:
  - entity: weather.appart
    type: weather-forecast
  - detail: 1
    entity: sensor.netatmo_statmet_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Netatmo extérieur
    type: sensor
  - entity: sensor.netatmo_statmet_interieur_temperature
    graph: line
    name: Netatmo intérieur
    type: sensor
  - detail: 1
    entity: sensor.lumi_lumi_weather_32f13908_temperature
    graph: line
    hours_to_show: 24
    name: Température Salon
    type: sensor
  - detail: 2
    entity: sensor.lumi_lumi_weather_temperature
    graph: line
    hours_to_show: 24
    type: sensor
  icon: mdi:weather-cloudy
  path: weather
  title: Weather
- badges:
  - entity: person.pierre
  cards:
  - entities:
    - entity: person.pierre
    type: map
  icon: mdi:account
- badges: []
  cards:
  - entities:
    - entity: sensor.switch_power
      name: Interrupteur
    - entity: sensor.lumi_lumi_weather_32f13908_power
    - entity: sensor.lumi_lumi_weather_power
    - entity: sensor.lumi_lumi_sensor_magnet_aq2_battery
      name: Gas Meter
    type: entities
  icon: mdi:battery-50
  path: power
  title: Power
