background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  voice_hide: true
title: Appart
views:
- badges:
  - entity: person.pierre
  - entity: sun.sun
  cards:
  - entities:
    - light.chambre
    - light.entree
    - light.salon
    title: Lights
    type: entities
  - entity: light.chambre
    type: light
  - entity: weather.appart
    type: weather-forecast
  - entity: media_player.spotify_pierre_berger
    type: media-control
  - entity: sensor.netatmo_statmet_exterieur_temperature
    graph: line
    hours_to_show: 24
    name: Saint Germain
    type: sensor
  - entities:
    - entity: sensor.netatmo_statmet_exterieur_max_temp
    - entity: sensor.netatmo_statmet_exterieur_min_temp
    - entity: sensor.netatmo_statmet_exterieur_temperature
    show_icon: false
    show_name: true
    show_state: true
    type: glance
  - entities:
    - entities:
      - input_select.theme
      head:
        entity: input_boolean.dark_mode
        name: Dark Mode
      type: custom:fold-entity-row
    show_header_toggle: false
    type: entities
  icon: mdi:home
  path: default_view
  title: Home
- badges: []
  cards:
  - icon: mdi:json
    icon_height: 20px
    name: Convert lovelace
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: shell_command.convert_lovelace
    type: button
  icon: mdi:home-automation
