---
- platform: template
  sensors:
    gas_meter:
      friendly_name: Gas Meter
      value_template: "{{ states ('counter.gas_counter') | float * 0.01}}"
      unit_of_measurement: 'm³'
      icon_template: 'mdi:fire'
      device_class: gas
      attribute_templates:
        state_class: total_increasing
