---
name: Home Assistant CI
on: [push]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install yamllint
      - run: yamllint .
